apps/main_app/urls.py
from apps.main_app.views import IndexView
from django.urls import path

app_name = 'main_app'

urlpatterns = [
    path('', IndexView.as_view(template_name='main_app/index.html'), name='index'),

    # path('api/crawl/', views.crawl, name='crawl'),
]


# This is required for static files while in development mode. (DEBUG=TRUE)
# No, not relevant to scrapy or crawling :)
# if settings.DEBUG:
#     urlpatterns += static.static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main_app.urls'))
]

apps/main_app/models.py
import json
from django.db import models
from django.utils import timezone


class SiteData(models.Model):
    unique_id = models.CharField(primary_key=True, max_length=100, null=False)
    created_at = models.DateTimeField(default=timezone.now)
    google_results = models.TextField(blank=True)
    site_data = models.TextField(blank=True)  # クロールしたdataはpipelinesから送られてくる

    @property
    def to_dict(self):
        """ # viewsからmodelを呼び出した際、json形式で呼び出すための関数"""
        site_data = {
            'site_data': json.loads(self.site_data),
            'created_at': self.created_at,


        }
        return site_data


apps/main_app/forms.py
from django import forms

COUNT_CHOICES = (20, '20'), (30, '30'), (40, '40'), (50, '50')
# グーグル検索数を表す。1ページ10サイト単位、10件だけだと少なすぎるし、50以上は必要ない。


class IndexFrom(forms.Form):
    def __init__(self, *args, **kwargs):
        """親クラスのForm初期値を呼び出し、classにform-controlを適用させている。
            これによってformのみの記入で全体にbootstrapを効かせることが出来る
        """
        super(IndexFrom, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = "form-control"

    search_keyword = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '検索キーワードを入力してください'}),
        label='search_keyword',
        max_length=255,
        required=True,

    )
    search_count = forms.ChoiceField(
        label='search_count',
        widget=forms.Select,
        choices=COUNT_CHOICES,
        required=False
    )

    input_task_id = forms.CharField(
        # このフォームにはviewsから動的に初期値が渡される様になってある
        widget=forms.TextInput(attrs={'placeholder': 'task_id'}),
        label='input_task_id',
        max_length=255,
        required=False,

    )

    input_unique_id = forms.CharField(
        # このフォームにはviewsから動的に初期値が渡されるようになってある
        widget=forms.TextInput(attrs={'placeholder': 'unique_id'}),
        label='input_unique_id',
        max_length=255,
        required=False,

    )

apps/main_app/views.py
from django.shortcuts import render, get_object_or_404
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.views.generic import FormView
from urllib.parse import urlparse
from scrapyd_api import ScrapydAPI
from uuid import uuid4
from googlesearch import search
from .forms import IndexFrom
from .models import SiteData
import copy


scrapyd = ScrapydAPI('http://localhost:6800')

class IndexView(FormView):
    template_name = 'main_app/index.html'
    form_class = IndexFrom
    success_url = '/'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.search_keyword = None
        self.search_count = None
        self.task_id = None
        self.unique_id = None
        self.google_results = None
        self.site_data = None
        self.status = None

    def get(self, request, *args, **kwargs):
        self.search_keyword = request.GET.get('search_keyword')
        self.search_count = request.GET.get('search_count')
        self.task_id = request.GET.get('input_task_id')
        self.unique_id = request.GET.get('input_unique_id')
        self.google_results = self.google_search(request)
        self.crawl(request)
        self.fetch_site_data_from_db(request)

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # はじめに継承元のメソッドを呼び出す
        context['search_keyword'] = self.search_keyword
        context['search_count'] = self.search_count
        context['google_results'] = self.google_results
        context['task_id'] = self.task_id
        context['unique_id'] = self.unique_id
        context['status'] = self.status
        context['site_data'] = self.site_data
        print(self.site_data)
        self.extract_url_for_link()
        return context

    def get_initial(self):
        """フォームに動的な初期値を渡している"""
        initial = super().get_initial()
        initial['input_task_id'] = self.task_id
        initial['input_unique_id'] = self.unique_id
        return initial

    def google_search(self, request):
        """1ページ10件、stop=2で20件のグーグルの検索結果を返す。
        最大で50までとなっているindex.htmlで20～50の値を選べる。変数名serach_count
        searchで帰ってくるのはジェネレーター"""
        if request.method == 'GET' and self.search_keyword:

            try:
                google = []
                for url in search(self.search_keyword,
                                  lang='jp',
                                  stop=int(self.search_count),
                                  user_agent='Mozilla/5.0 (Windows NT 6.1)'
                                  'AppleWebKit/537.36 (KHTML, like Gecko)'
                                  'Chrome/28.0.1500.63 Safari/537.36'
                                  ):
                    google.append(copy.deepcopy(url))

                return google

            # この例外の方法は正しくないかもしれない。
            # エラーを表示する事はセキュリティ上よくないかもしれない じゃあどうするべきなのか
            except Exception as e:
                print('検索の段階でエラーが発生しました')
                print(str(type(e)))
                print(str(e.args))
                print(str(e))

    def crawl(self, request):
        """
        検索結果のurlのリストから最初のurlだけを1つ抜き出してトリガーとしてscrapyを動かしている
        urlリストはモデルからDBへ
        """
        if request.method == 'GET' and self.google_results and self.search_keyword:
            url = self.google_results  # 最初のurlだけをトリガーに使ってscrapyを動かす
            if not url[0]:
                return JsonResponse({'error': 'Missing  args'})

            if not is_valid_url(url[0]):
                return JsonResponse({'error': 'URL is invalid'})

            domain = urlparse(url[0]).netloc
            self.unique_id = str(uuid4())
            site_data = SiteData()
            site_data.unique_id = self.unique_id

            site_data.google_results = self.google_results
            site_data.save()
            settings = {
                'unique_id': self.unique_id,  # unique ID for each record for DB
                'USER_AGENT': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',

            }

            # 第一引数にscrapyのプルジェクト名、第二引数にスパイダー名をいれる
            self.task_id = scrapyd.schedule('scrapy_app',
                                            'blogspider',
                                            settings=settings,
                                            url=url[0],
                                            domain=domain,
                                            unique_id=self.unique_id,
                                            )

            return JsonResponse({'task_id': self.task_id, 'unique_id': self.unique_id, 'status': 'started'})
            # 大事なのはこのjsonでschedulを送ることそれでscrapydが働いてくれる

    def fetch_site_data_from_db(self, request):
        if request.method == 'GET'and self.task_id and self.unique_id:
            if not self.task_id or not self.unique_id:
                return JsonResponse({'error': 'Missing args'})

            self.status = scrapyd.job_status('scrapy_app', self.task_id)
            # 第一引数にscrapyのプロジェクト名を入れる

            if self.status == 'finished':
                try:
                    item = SiteData.objects.get(unique_id=self.unique_id)
                    # クロール前に作成したunique_idをつかってモデルからdataをとりだす
                    self.site_data = item.to_dict['site_data']

                    return JsonResponse({'data': item.to_dict['site_data']})

                except Exception as e:

                    return JsonResponse({'error': str(e)})
            else:
                return JsonResponse({'status': self.status})

    def extract_url_for_link(self):
        # d = []
        d = self.site_data
        print(d)
        # for i in self.site_data:

            # d.append(i.get('url'))
        # return(d)

def is_valid_url(url):
    validate = URLValidator()
    try:
        validate(url)  # check if url format is valid
    except ValidationError:
        return False

    return True

apps/main_app/templates/main_app/index.html


{% load static %}
<!doctype html>
<html lang="ja" xmlns="http://www.w3.org/1999/html">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main_app/style.css' %}">
    <title>Googleanker</title>
</head>
<body>

<div class="container" style="padding: 20px 0">
 <h1>GoogleRanker　ググらんかー</h1>
    <p>
    <a class="btn btn-primary"
        data-toggle="collapse"
        href="#multiCollapseExample1"
        role="button" aria-expanded="false"
        aria-controls="multiCollapseExample1">使い方
    </a>
    </p>
    <div class="row">
        <div class="col">
            <div class="collapse multi-collapse" id="multiCollapseExample1">
                <div class="card card-body">
                    <p>{{ site_url }}</p>
                    <p>サイトのタイトルやh1~6の一覧を表示します。ライバルのサイトがどんなキーワードでサイト作っている見るために作りました。
                    <P>自分のサイトが上に行かない時は上位のサイトがどんなキーワードを使っているか調べて見ましょう。ヒントが見つかるかも</P>
                    <p>1. 検索したいキーワードと検索件数(20~50)を入力してください</p>
                    <p>2. Searchを押すと自動的にサイトデータの取得が開始されます</p>
                    <p>3. 取得が終わった後にGetを押すとサイトデータが表示できます</p>
                    <p>&nbsp;&nbsp;&nbsp;  取得には時間がかかります。ごめんね。検索が終了しているかはクローラーロボの状態を確認してください</p>
                    <p>4. IDが表示されている状態でGetボタンを押してください</p>
                    <p>&nbsp;&nbsp;&nbsp;   IDはSearchが終わると自動的に表示されます
                    <p>クローラーロボの状態は3種類</p>
                    <p>pending:保留中 => IDが入力されているを確認してGetボタンを押して下さい</p>
                    <p>running:取得中 => しばらくしてから再度Getボタンを押して下さい</p>
                    <p>finished:検索終了 => Getボタンを押すと検索結果が表示されます</p>
                    <p>たとえば20件取得しようとして表示が20件に満たない事があります。その場合は30件取得するなどして下さい。</p>
                    <p>あんまりGetを連打しないでくださいね。速くなりませんよ<p>
                </div>
            </div>
        </div>
    </div>

{#ここからgoogle検索結果#}
    <div class="container" style="padding: 20px 0">

        <form action="{% url "main_app:index" %}" method="get">

        <div class="form-group">
        {{ form.search_keyword }}
        </div>

        <div class="form-group">
        {{ form.search_count }}
        </div>

        <button type="submit" class="btn btn-primary mb-2">Search</button>

        </form>

    </div>



    <div class="container" style="padding: 20px 0">
    {% if task_id and unique_id != None %}
        <h4>クローラーの状態 :【{{ status }}】</h4>

    {% endif %}
    <form action="{% url "main_app:index" %}" method="get">

    <div class="form-group">
        <label for="input_task_id">Task_ID</label>
        {{ form.input_task_id }}

    </div>

    <div class="form-group">
    <label for="input_unique_id">Unique_ID</label>
    {{ form.input_unique_id }}

    </div>

        <button type="submit" class="btn btn-primary mb-2">Get</button>
    </form>
    </div>
{#============ここからsite_dataの表示=======================================#}
    <div>
    {% if site_data != None %}
{#    <li class="list-group" style="max-width: 1000px;">#}
        {% for dict in site_data %}
            {% for site_data_key, site_data_value in dict.items %}

                {% if site_data_key != 'rank' %}{# 検索順位は最初に表示しているためif文で消してある#}
                    <li class="list-group-item bg-light">{{ dict.rank }}位【{{ site_data_key }}】<br>{{ site_data_value | urlize }}</li>
                {% endif %}
            {% endfor %}
            <br>
        {% endfor %}


    {% endif %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
{#</div>#}
</div>
</body>

</html>